services:
  - type: web
    name: sakthi-spices-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false

  - type: web
    name: sakthi-spices-frontend
    env: node
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: sakthi-spices-backend
          envVarKey: RENDER_EXTERNAL_URL
    domains:
      - billing.sakthi-dev.in
